import type { TimelineEventType } from '@starpay/types';

export const TIMELINE_LABELS: Record<TimelineEventType, string> = {
  ORDER_CREATED: 'Order Created',
  QR_GENERATED: 'QR Code Generated',
  INTENT_OPENED: 'UPI App Opened',
  ANDROID_EVENT_RECEIVED: 'SMS Received',
  SMS_PARSED: 'Payment Details Extracted',
  VERIFICATION_STARTED: 'Verification Started',
  AMOUNT_VERIFIED: 'Amount Verified',
  TIME_WINDOW_CHECKED: 'Time Window Checked',
  UTR_UNIQUENESS_CHECKED: 'UTR Uniqueness Checked',
  FRAUD_CHECK_PASSED: 'Fraud Check Passed',
  FRAUD_CHECK_FAILED: 'Fraud Check Failed',
  APPROVED: 'Payment Approved',
  FALLBACK_TRIGGERED: 'Manual Review Required',
  MANUAL_SUBMITTED: 'Customer Submitted Details',
  MANUAL_APPROVED: 'Manually Approved',
  MANUAL_REJECTED: 'Manually Rejected',
  INVOICE_GENERATED: 'Invoice Generated',
  NOTIFICATION_SENT: 'Notification Sent',
  ORDER_EXPIRED: 'Order Expired',
  ORDER_FAILED: 'Order Failed',
};

export const TIMELINE_ICONS: Record<TimelineEventType, string> = {
  ORDER_CREATED: '💳',
  QR_GENERATED: '📷',
  INTENT_OPENED: '📱',
  ANDROID_EVENT_RECEIVED: '📬',
  SMS_PARSED: '🔍',
  VERIFICATION_STARTED: '⚡',
  AMOUNT_VERIFIED: '✔️',
  TIME_WINDOW_CHECKED: '⏰',
  UTR_UNIQUENESS_CHECKED: '🔐',
  FRAUD_CHECK_PASSED: '🛡️',
  FRAUD_CHECK_FAILED: '🚨',
  APPROVED: '✅',
  FALLBACK_TRIGGERED: '⚠️',
  MANUAL_SUBMITTED: '📝',
  MANUAL_APPROVED: '👍',
  MANUAL_REJECTED: '👎',
  INVOICE_GENERATED: '📄',
  NOTIFICATION_SENT: '📧',
  ORDER_EXPIRED: '⏱️',
  ORDER_FAILED: '❌',
};

export const TIMELINE_COLORS: Record<TimelineEventType, string> = {
  ORDER_CREATED: 'bg-blue-500',
  QR_GENERATED: 'bg-violet-500',
  INTENT_OPENED: 'bg-violet-400',
  ANDROID_EVENT_RECEIVED: 'bg-indigo-500',
  SMS_PARSED: 'bg-indigo-400',
  VERIFICATION_STARTED: 'bg-violet-500',
  AMOUNT_VERIFIED: 'bg-emerald-500',
  TIME_WINDOW_CHECKED: 'bg-emerald-400',
  UTR_UNIQUENESS_CHECKED: 'bg-emerald-400',
  FRAUD_CHECK_PASSED: 'bg-emerald-500',
  FRAUD_CHECK_FAILED: 'bg-red-500',
  APPROVED: 'bg-emerald-500',
  FALLBACK_TRIGGERED: 'bg-amber-500',
  MANUAL_SUBMITTED: 'bg-amber-400',
  MANUAL_APPROVED: 'bg-emerald-500',
  MANUAL_REJECTED: 'bg-red-500',
  INVOICE_GENERATED: 'bg-blue-400',
  NOTIFICATION_SENT: 'bg-blue-400',
  ORDER_EXPIRED: 'bg-slate-500',
  ORDER_FAILED: 'bg-red-500',
};
